#services:
#  db:
#    image: postgres
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USERNAME: postgres
#      POSTGRES_PASSWORD: 1234
#      POSTGRES_DB: HRManagementSystem

version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: springbooot-app
    build: .
    ports:
      - 8000:8080
    environment:
      POSTGRES_DB: HRManagementSystem
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_PORT: 5432
#  mysqldb:
#    container_name: postgresdb
#    image: postgres
#    volumes:
#      -  C:\Users\DataTex\Desktop\db:/var/lib/postgres
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_DATABASE: HRManagementSystem
#      POSTGRES_ROOT_PASSWORD: 1234
